In [2]:
import numpy as np
from numpy import array
from numpy import arange
import pandas as pd

Q1: make 9X2 int array in a range b/w 320 to 500 having difference between each element is 10?

In [4]:
x=np.arange(320,500,10) # using arange 
x.reshape(9,2)

array([[320, 330],
       [340, 350],
       [360, 370],
       [380, 390],
       [400, 410],
       [420, 430],
       [440, 450],
       [460, 470],
       [480, 490]])

In [9]:
k=np.linspace(320,500,18).reshape(9,2) #using linspace if deference is not of 10 or (any difference).
k


array([[320.        , 330.58823529],
       [341.17647059, 351.76470588],
       [362.35294118, 372.94117647],
       [383.52941176, 394.11764706],
       [404.70588235, 415.29411765],
       [425.88235294, 436.47058824],
       [447.05882353, 457.64705882],
       [468.23529412, 478.82352941],
       [489.41176471, 500.        ]])

Q2: From a 3*3 numPy array return numbers in the second column from all rows?
import numpy as nP
DzoneArray = np.array([[10 ,20, 30], [40, 50, 60], [70, 80, 90]])

In [19]:
DzoneArray=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(DzoneArray)
print("modified matrix ")
DzoneArray[0:,1]

[[10 20 30]
 [40 50 60]
 [70 80 90]]
modified matrix 


array([20, 50, 80])

Q3 Extract odd rows and even columns from given Numpy array Separately?
TestArray = np.array([[4 ,8, 33, 29], [20,41, 28, 12], [36 ,18, 44, 37], [52 ,56, 19, 64], [68 ,50, 76, 80]]

In [30]:
TestArray=pd.DataFrame([[4,8,33,29],[20,41,28,12],[36,18,44,37],[52,56,19,64],[68,50,76,80]],index=["row1","row2","row3","row4","row5"],columns=["col1","col2","col3","col4"])
TestArray


col1  col2  col3  col4
row1     4     8    33    29
row2    20    41    28    12
row3    36    18    44    37
row4    52    56    19    64
row5    68    50    76    80

In [32]:
#printing odd rows
TestArray.loc[['row1','row3','row5']]

col1  col2  col3  col4
row1     4     8    33    29
row3    36    18    44    37
row5    68    50    76    80

In [35]:
# printing even cols
TestArray[['col2','col4']]

col2  col4
row1     8    29
row2    41    12
row3    18    37
row4    56    64
row5    50    80

Q4 Add the following tow NumPy arrays and in resultant array calculate the square of each number?import numpy as np.
arr1=np.array([[5,8,6],[21,20,27]])
arr2=np.array([[15,33,24],[4,5,1]])

In [39]:
arr1=np.array([[5,8,6],[21,20,27]])
arr2=np.array([[15,33,24],[4,5,1]])
arr3=arr1+arr2
arr3

array([[20, 41, 30],
       [25, 25, 28]])

In [40]:
np.square(arr3) # preforming square operatins

array([[ 400, 1681,  900],
       [ 625,  625,  784]], dtype=int32)

Q5 Split the array into three equal-sized sub-arrays?
(Create an 9X3 array from a range between 13 to 40 such that the difference between each element is 1 and then split the array into three equal-sized sub-arrays.)

In [49]:
create=np.arange(13,40).reshape(9,3)
create

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33],
       [34, 35, 36],
       [37, 38, 39]])

In [52]:
s_create=np.split(create,3)#spliting the create matrix in 3 sub arrays
s_create

[array([[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21]]), array([[22, 23, 24],
        [25, 26, 27],
        [28, 29, 30]]), array([[31, 32, 33],
        [34, 35, 36],
        [37, 38, 39]])]

Q6 Sort the given NumPy array:
by second row
by second column
import numpy as np
Arr1=np.array([[11,43,49],[82,50,12],[53,23,77]])

In [53]:
Arr1=np.array([[11,43,49],[82,50,12],[53,23,77]])
Arr1

array([[11, 43, 49],
       [82, 50, 12],
       [53, 23, 77]])

In [69]:
Arr1.sort(axis=0) # for row sorting
Arr1

array([[11, 23, 12],
       [43, 49, 53],
       [50, 77, 82]])

In [70]:
Arr1.sort(axis=1) # for col sorting
Arr1

array([[11, 12, 23],
       [43, 49, 53],
       [50, 77, 82]])

Q7 In a 2-D numpy array print max from axis 0 and min from axis 1?
import numpy as np
dzoneArray=np.array([[11,43,49],[82,50,12],[53,23,77]]

In [72]:
dzoneArray=np.array([[11,43,49],[82,50,12],[53,23,77]])
dzoneArray

array([[11, 43, 49],
       [82, 50, 12],
       [53, 23, 77]])

In [77]:
mx=np.max(dzoneArray,axis=0)# finding max no 
np.max(mx)

82

In [82]:
mn=np.min(dzoneArray,axis=1)# finding min no
np.min(mn)

11

Finding maximum no from each row

In [105]:
dzoneArray=pd.DataFrame([[11,43,49],[82,50,12],[53,23,77]],index=["row1","row2","row3"],columns=["col1","col2","col3"])
dzoneArray

col1  col2  col3
row1    11    43    49
row2    82    50    12
row3    53    23    77

In [116]:
# extracting max element from all row
dzoneArray.loc['row1'].max()

49

In [117]:
dzoneArray.loc['row2'].max()

82

In [120]:
dzoneArray.loc['row3'].max()

77

In [125]:
# extracting min element from all col
dzoneArray['col1'].min()

11

In [126]:
dzoneArray['col2'].min()

23

In [127]:
dzoneArray['col3'].min()

12

Q8 From a given NumPy array delete second column and insert a new column in its place?
import numpy
Arr1=np.array([[11,43,49],[82,50,12],[53,23,77]])
NwCol=np.array([[10,10,10]])

In [121]:
Arrr1=pd.DataFrame([[11,43,49],[82,50,12],[53,23,77]],index=["row1","row2","row3"],columns=["col1","col2","col3"])
Arrr1

col1  col2  col3
row1    11    43    49
row2    82    50    12
row3    53    23    77

In [122]:
Arrr1.drop('col2',axis=1,inplace=True)
Arrr1

col1  col3
row1    11    49
row2    82    12
row3    53    77

In [123]:
Arrr1['NwCol']=10
Arrr1

col1  col3  NwCol
row1    11    49     10
row2    82    12     10
row3    53    77     10

----------------------End----------------------------------